### ISSUE TITLE
installing on ubuntu 20.04 and get error

### ISSUE THREAD

**Issue by drizzt09** [philamp/jellygrail#2]
installing on ubuntu 20.04 and get error:
` => ERROR [stage-1 14/24] RUN python3 -m pip install -r requirements.txt                                                          2.5s
------
 > [stage-1 14/24] RUN python3 -m pip install -r requirements.txt:
1.589 error: externally-managed-environment
1.589
1.589 × This environment is externally managed
1.589 ╰─> To install Python packages system-wide, try apt install
1.589     python3-xyz, where xyz is the package you are trying to
1.589     install.
1.589
1.589     If you wish to install a non-Debian-packaged Python package,
1.589     create a virtual environment using python3 -m venv path/to/venv.
1.589     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
1.589     sure you have python3-full installed.
1.589
1.589     If you wish to install a non-Debian packaged Python application,
1.589     it may be easiest to use pipx install xyz, which will manage a
1.589     virtual environment for you. Make sure you have pipx installed.
1.589
1.589     See /usr/share/doc/python3.11/README.venv for more information.
1.589
1.589 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
1.589 hint: See PEP 668 for the detailed specification.
------
Dockerfile:122
--------------------
 120 |     # COPY rclone.conf /root/.config/rclone/
 121 |     COPY root/requirements.txt /requirements.txt
 122 | >>> RUN python3 -m pip install -r requirements.txt
 123 |
 124 |     # nginx
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -m pip install -r requirements.txt" did not complete successfully: exit code: 1
`

**Comment by philamp** [comment]
ok, the base docker image must have changed and I should have installed in venv mode. Will fix that as soon as possible
Thanks for your feedback :)

**Comment by philamp** [comment]
@drizzt09 : this is now fixed thanks to https://github.com/laster13 who had the same issue forking my repo, don't know if it's related to docker base image changed or host system / host docker having different rules than my host system, Anyway using python venv is a good practice

**Comment by drizzt09** [comment]
Thanks
